### ISSUE TITLE
com.powsybl.cgmes.model.CgmesModelException: nominalVoltage not found for BaseVoltage

### ISSUE THREAD

**Issue by chadhat** [powsybl/powsybl-distribution#43]
### Describe the current behavior

We are trying to run the convert-network functionality of itools. Our data is XML files from TYNDP 2020. We are trying to run the command as follows:

itools convert-network --input-file DE.xml --output-format XIIDM --output-file XIIDM\DE

However, we encounter the following error:

com.powsybl.cgmes.model.CgmesModelException: nominalVoltage not found for BaseVoltage 7891a026ba2c42098556665efd13ba94
        at com.powsybl.cgmes.conversion.elements.VoltageLevelConversion.convert(VoltageLevelConversion.java:62)
        at com.powsybl.cgmes.conversion.Conversion.convert(Conversion.java:460)
        at com.powsybl.cgmes.conversion.Conversion.convert(Conversion.java:178)
        at com.powsybl.cgmes.conversion.CgmesImport.importData1(CgmesImport.java:176)
        at com.powsybl.cgmes.conversion.CgmesImport.importData(CgmesImport.java:170)
        at com.powsybl.iidm.network.Network.read(Network.java:128)
        at com.powsybl.iidm.network.tools.ConversionTool.run(ConversionTool.java:111)
        at com.powsybl.tools.CommandLineTools.run(CommandLineTools.java:165)
        at com.powsybl.tools.Main.main(Main.java:30)

There is no nominalVoltage in our TYNDP files. Any help or pointers are appreciated.

### Environment

- Powsybl version powsybl-distribution-2024.3.0
- OS: Windows 11

**Comment by olperr1** [comment]
Sorry, we didn't see this issue!

powsybl-distribution is just a small repository providing a distribution of the different libraries of PowSyBl (see [here](https://powsybl.readthedocs.io/en/latest/releasetrain.html#the-powsybl-starter-and-powsybl-distribution-artifacts)). All the business code is in the different repositories of the release train components (see [here](https://powsybl.readthedocs.io/en/latest/releasetrain.html#release-train)).

For business questions, the preferred way is to ask them in one of our Slack channels (access link available [in this page](https://www.powsybl.org/pages/community/contact.html)). In this particular case, the `#cgmes` one should be the most suitable.

Since your question is already more than a year old, I assume that you may have found a way to tackle this problem, so I close this issue.
If it is not the case and you still have a problem, you can ask for help on our Slack `#cgmes` channel.
